### ISSUE TITLE
To update changes from eo-runtime

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-collections#10]
We need to synchronise all updated from `collections` package of eo-runtime, accoding to this: https://github.com/objectionary/eo/issues/936

**Comment by Graur** [comment]
@EugeneDar please, help to do it

**Comment by EugeneDar** [comment]
@Graur I think you can close it.

**Comment by Graur** [comment]
@rultor release, tag is `0.0.1`

**Comment by Graur** [comment]
@rultor release, tag is `0.0.1`

**Comment by Graur** [comment]
@rultor release, tag is `0.0.1`

**Comment by Graur** [comment]
@rultor release, tag is `0.0.2`

**Comment by Graur** [comment]
@EugeneDar thanks!
