### ISSUE TITLE
list.inflated should return list

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-collections#103]
Now list.inflated returns array object. But it should return list as other list methods

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#137](https://github.com/objectionary/eo-collections/issues/137) is still not solved.

**Comment by 0pdd** [comment]
@EugeneDar the only puzzle [#137](https://github.com/objectionary/eo-collections/issues/137) is solved here.
