### ISSUE TITLE
gt, lt, gte, lte for "list"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#111]
I suggest we implement `.gt`, `.lt`, `.gte`, and `.lte` for the `list` object, similar to how they are implemented in Haskell.

**Comment by yegor256** [comment]
@EugeneDar maybe you can help?

**Comment by EugeneDar** [comment]
@yegor256 sure

**Comment by EugeneDar** [comment]
@yegor256 just in case, we want to get this logic of operation:
```
[3,4,2] > [3,4]  
True  

[0, 99, 99, 99] < [1, 0]
True
```

**Comment by yegor256** [comment]
@EugeneDar this is not how it works in Haskell

**Comment by EugeneDar** [comment]
@yegor256 file:///home/eugene/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BA%D0%B8%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202023-02-16%2015-37-31.png

**Comment by EugeneDar** [comment]
@yegor256 
![Снимок экрана от 2023-02-16 15-37-31](https://user-images.githubusercontent.com/68021590/219367094-7f9afbcd-6e19-4273-8f8e-dfd68a822024.png)

**Comment by yegor256** [comment]
@EugeneDar oops, sorry, I thought there was `>` in both examples. yes, you are right, let's implement it this way.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#147](https://github.com/objectionary/eo-collections/issues/147) is still not solved.
