### ISSUE TITLE
list.last-index-of

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#115]
Let's create a new method `last-index-of`, which will find the position of an object in the list starting from the end of the list, comparing objects using `.eq`:

```
eq.
  index-of.
    list
      * "hi" 2 "hi" 4 5
      "hi"
  2
```

If the object is not in the list, `-1` must be returned.

**Comment by Graur** [comment]
@EugeneDar please, help us here

**Comment by EugeneDar** [comment]
@Graur sure, assign me
