### ISSUE TITLE
list.withi

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#116]
Let's create a new method `.withi` (with, by index), which can replace an element in the list:

```
eq.
  withi.
    list
      * 1 2 3 4 5
    3
    "hello"
  * 1 2 3 "hello" 4 5
```

**Comment by maxonfjvipon** [comment]
@Graur I can help, can you please assign me?

**Comment by Graur** [comment]
@maxonfjvipon But this issue has been already assigned. Let's ask @MikhailLipanin about his progress here

**Comment by maxonfjvipon** [comment]
@MikhailLipanin do you have any progress here?

**Comment by MikhailLipanin** [comment]
@maxonfjvipon, let me pls try to do this by myself a one day more. If I will fail, you will do this, WDYT?

**Comment by maxonfjvipon** [comment]
@MikhailLipanin sure, thanks
