### ISSUE TITLE
list.withouti

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#117]
Now we have the method `.without`, which removes the i-th element. I suggest renaming this method to `withouti` and introducing a new method `without`, which should replace all object that are `.eq` to the provided one:

```
eq.
  without.
    list 
      * 1 2 1 2 1 5
    2
  * 1 1 1 5
```

**Comment by Graur** [comment]
@levBagryansky Please, help us here

**Comment by maxonfjvipon** [comment]
@Graur I may help here, could you please assign me?

**Comment by levBagryansky** [comment]
@maxonfjvipon I am already solving it.
