### ISSUE TITLE
map.contains-key and map.contains-value

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#119]
Let's create a new method which will return `TRUE` if the map has the provided key. Also, a method to check whether a value is there would be great to have.

**Comment by Graur** [comment]
@EugeneDar Can you help with this?

**Comment by EugeneDar** [comment]
@Graur sure, assign me

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#151](https://github.com/objectionary/eo-collections/issues/151) is still not solved.
