### ISSUE TITLE
set

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#120]
Let's create a new object `org.eolang.collections.set`, which should be a decorator of the `list`, but make a guarantee that the list has only unique objects:

```
eq.
  with.
    QQ.collections.set
      QQ.collections.list
        * 1 2 3 1 2 5
    4
  * 1 2 3 5 4
```

**Comment by maxonfjvipon** [comment]
@yegor256 can you please assign me?

**Comment by yegor256** [comment]
@maxonfjvipon sure, go ahead

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#140](https://github.com/objectionary/eo-collections/issues/140) is still not solved.
