### ISSUE TITLE
range

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#122]
Let's create a new object `org.eolang.range` to represent a range as an array:

```
eq.
  range
    1
    [i] (i.plus 3 > @)
    8
  * 1 4 7
```

It takes three arguments: the first object in the range, the function to apply in order to generate the next element, and the maximum.

**Comment by maxonfjvipon** [comment]
@yegor256 `range` function exists in many programming languages. 

For example in php it takes also 3 arguments: first number, last (end, maximum) number and the step. If step is not specified it will default to 1.

I suppose eo range is able to work not only with numbers but with any objects, so default "step" does not fit here, but I would suggest to make generate function the last element. I think it will be more intuitive for developers.

Also if you don't mind I would try to implement it

**Comment by yegor256** [comment]
@maxonfjvipon sure, go ahead
