### ISSUE TITLE
"range" doesn't need to get a "func"

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#133]
The design of `range` is functional, not object-oriented. We expect the user to provide a "function" as the third argument of `range`. Instead, we should expect the first argument to have a method `next`:

```
eq.
  range
    []
      1 > @
      [] > next
        ^.@.plus 1 > @
    4
  * 1 2 3
```

This would be "object oriented".

**Comment by yegor256** [comment]
@maxonfjvipon what do you think?

**Comment by maxonfjvipon** [comment]
@yegor256 I don't really understand how we can get object `3` while building a list?

It seems after we got `2` <-- `1.plus 1` <-- `^.@.plus 1` we should recreate an abstract object with inner object `next` but with `@ = 2` and somehow pass there the `next` rule?

**Comment by yegor256** [comment]
@maxonfjvipon how about this:

```
[i] > x
  i > @
  & (^.i.plus 1) > next
eq.
  range
    x 0
    4
  * 1 2 3
```

This doesn't look compact, but it will work. How to make it more compact -- we should think. It's impossible at the moment with the current EO syntax to make a copy of an abstract object right when it's being formed.

**Comment by maxonfjvipon** [comment]
@yegor256 that's more understandable. I can try to implement it

**Comment by yegor256** [comment]
@maxonfjvipon something like this would be convenient:

```
eq.
  range
    [i]
      i > @
      $ (i.plus 1) > next
      0 > i
    4
  * 1 2 3
```

**Comment by maxonfjvipon** [comment]
@yegor256 that's better, but won't not really intuitive for people who use `range(start, end, predicate)` entire life)
 Let's try

**Comment by maxonfjvipon** [comment]
@yegor256 it does not seem work:
```
[] > new-range
  rrange > rng!
    [i]
      i > @
      $ (i.plus 1) > next
      1 > i
    10
  assert-that > @
    list rng
    $.equal-to
      list
        * 1 2 3 4 5 6 7 8 9
```

I get: "[ERROR] net.sf.saxon.style.XSLText@ed6009a: Critical error identified: The name "i" is already in use; "

**Comment by maxonfjvipon** [comment]
This also works but it's kinda complicated
```
range > rng!
  [i...] > x
    if. > ii
      i.length.eq 0
      1
      i.at 0
    x (ii.plus 1) > next
    ii > @
  10
```

**Comment by yegor256** [comment]
@maxonfjvipon this one is perfect:

```
range > rng!
  []
    [i] > x
      i > @!
      x (@.plus 1) > next
    x 1 > @
  10
```
