### ISSUE TITLE
Optimize `list.reducedi`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-collections#135]
`list.reducedi` - is one of the important and key object is `eo-collections` and it can be optimized - there is one unwanted and heavy dataization and we can get rid of `seq` here:

```
[a f] > reducedi
  if. > @
    eq.
      0
      length.
        arr
    a
    rec-reduced
      * a 0
      f
      arr

  [acc-index func carr] > rec-reduced
    acc-index.at 0 > acc
    acc-index.at 1 > index
    seq > @
      func > new-acc!     # <--- here we are guaranteed to do dataize func because of seq
        acc
        index
        carr.at index
      if.
        (index.plus 1).eq (carr.length)
        new-acc
        rec-reduced
          *
            func    # <--- here func is created again
              acc
              index
              carr.at index
            index.plus 1
          func
          carr
```

I tried to optimize it and I got time of execution of `set` object tests decreased from _2:17_ to _1:47_ on my machine

@yegor256 please have a look. If it worths it, could you please assign me?

**Comment by maxonfjvipon** [comment]
@yegor256 @Graur WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon I think it's definitely a bug we should fix
