### ISSUE TITLE
map.rebuild doesn't need to be an atom

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-collections#15]
If we look at the current asymptotics of the other methods in the map class, we can make a rebuild method without using Java and without worsening the asymptotics.

**Comment by yegor256** [comment]
@EugeneDar moved

**Comment by 0pdd** [comment]
@EugeneDar 5 puzzles [#69](https://github.com/objectionary/eo-collections/issues/69), [#70](https://github.com/objectionary/eo-collections/issues/70), [#71](https://github.com/objectionary/eo-collections/issues/71), [#72](https://github.com/objectionary/eo-collections/issues/72), [#73](https://github.com/objectionary/eo-collections/issues/73) are still not solved.
