### ISSUE TITLE
list.eachi doesn't exist

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#181]
I believe, we should have this attribute the `list` object, in order to iterate with an index.

**Comment by yegor256** [comment]
@maxonfjvipon pls, help

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#187](https://github.com/objectionary/eo-collections/issues/187) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#189](https://github.com/objectionary/eo-collections/issues/189) is still not solved; solved: [#187](https://github.com/objectionary/eo-collections/issues/187).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#189](https://github.com/objectionary/eo-collections/issues/189), [#194](https://github.com/objectionary/eo-collections/issues/194) are still not solved; solved: [#187](https://github.com/objectionary/eo-collections/issues/187).
