### ISSUE TITLE
list.eo:259-263: Object "rec-filtered" inside "filteredi"...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-collections#184]
The puzzle `182-0835ea5c` from #182 has to be resolved: 

https://github.com/objectionary/eo-collections/blob/475ea4366702476c01de287a93b9002cc11c2117/src/main/eo/org/eolang/collections/list.eo#L259-L263

The puzzle was created by @maxonfjvipon on 31-May-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by maxonfjvipon** [comment]
@yegor256 please assign me
