### ISSUE TITLE
wrong list object naming

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-collections#20]
We need to change names of `reduce`, `reducei`, `map` and `mapi` objects according to [this](https://arxiv.org/pdf/2206.02585.pdf) paper.
Also we need to apply these changes to all tests.

**Comment by yegor256** [comment]
@Graur moved

**Comment by Graur** [comment]
@yegor256 Thanks!
@levBagryansky go ahead

**Comment by 0pdd** [comment]
@Graur 3 puzzles [#22](https://github.com/objectionary/eo-collections/issues/22), [#23](https://github.com/objectionary/eo-collections/issues/23), [#24](https://github.com/objectionary/eo-collections/issues/24) are still not solved.

**Comment by Graur** [comment]
@yegor256 we need to release `eo-collections` to 0.0.3 version. Please help us

**Comment by Graur** [comment]
@levBagryansky Thanks!

**Comment by 0pdd** [comment]
@Graur 2 puzzles [#23](https://github.com/objectionary/eo-collections/issues/23), [#24](https://github.com/objectionary/eo-collections/issues/24) are still not solved; solved: [#22](https://github.com/objectionary/eo-collections/issues/22).

**Comment by 0pdd** [comment]
@Graur the puzzle [#23](https://github.com/objectionary/eo-collections/issues/23) is still not solved; solved: [#22](https://github.com/objectionary/eo-collections/issues/22), [#24](https://github.com/objectionary/eo-collections/issues/24).

**Comment by 0pdd** [comment]
@Graur all 3 puzzles are solved here: [#22](https://github.com/objectionary/eo-collections/issues/22), [#23](https://github.com/objectionary/eo-collections/issues/23), [#24](https://github.com/objectionary/eo-collections/issues/24).
