### ISSUE TITLE
`eo 0.32.0` with `eo-maven-plugin 0.32.0` can't be versioned up in objectionary

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-collections#203]
This [build](https://github.com/objectionary/home/actions/runs/6423616746/job/17442507664?pr=187) fails because of parsing errors in `multimap-tests`

**Comment by levBagryansky** [comment]
@yegor256 can we release it in order to update home? to 0.10.1

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.1`

**Comment by levBagryansky** [comment]
@maxonfjvipon please help

**Comment by Graur** [comment]
@rultor release, tag is `0.10.2`
