### ISSUE TITLE
upgrade to EO 0.28.2

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#33]
We should upgrade to 0.28.2 and release a new version. There will be some issues, I suspect.

**Comment by yegor256** [comment]
@Graur please, help with this one

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#37](https://github.com/objectionary/eo-collections/issues/37) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#37](https://github.com/objectionary/eo-collections/issues/37) is solved here.
