### ISSUE TITLE
The array needs a comparison method

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-collections#58]
In most (or even all) programming languages, object comparison is one of the most fundamental operations. And in case we have such a data structure as an array, then comparing two arrays for equality is more fundamental than for example adding a new element to the array (of course, EOLANG does not have to rely on other languages, but not to be unfounded, the proof can be found in languages such as C++).
However, we have the `array.with` method in the array class itself, and the `list.eq` method only in its wrapper (or rather decorator).
Additionally, I note that in our code it also occurs when there is a redefinition of methods in classes and their decorators. Such as `text.slice` and `string.slice`. 

Based on all of the above, that there is every reason to add the method `array.eq`.

**Comment by EugeneDar** [comment]
Additionally, we compare arrays very often in our tests, and the presence of `array.eq` would make such a comparison extremely easy, both in general and for nested arrays.

**Comment by EugeneDar** [comment]
@yegor256 @Graur what do you think?

**Comment by yegor256** [comment]
@EugeneDar you do know that in Java we don't have such a method, right? Also, we don't have it in C++?...

**Comment by EugeneDar** [comment]
@yegor256 Yes, that's my mistake, I forgot that addresses are compared. 
What about overriding methods in decorators?

**Comment by EugeneDar** [comment]
@yegor256 I also have a question about the comparison method in 'list'. Why doesn't it compare bytes?

**Comment by yegor256** [comment]
@EugeneDar in Java we have [Arrays.equals](https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#equals(boolean%5B%5D,%20boolean%5B%5D)) -- it does exactly what we do in `list.eq` -- goes item by item and calling `eq` on them

**Comment by yegor256** [comment]
@EugeneDar `list.eq` doesn't compare bytes, it calls `eq` on each array item it finds. What happens in those `eq` methods -- it's up to the objects

**Comment by EugeneDar** [comment]
@yegor256 So there's no way I can check if there's another array in the array, because I'll get an error.

**Comment by yegor256** [comment]
@EugeneDar there is not reflection in EO. You can't check whether an object **is an** array. You can only expect it to **behave as an** array.

**Comment by EugeneDar** [comment]
@yegor256 I'm sorry, I probably didn't express myself correctly. I meant that it seems strange to me that if two elements have method `eq` then comparing them can throw an error, I thought any comparison is TRUE or FALSE (if you need an explanation I can give you an example why this might be a problem).

**Comment by yegor256** [comment]
@EugeneDar comparing two elements in Java may also lead to a runtime exception

**Comment by EugeneDar** [comment]
@yegor256 maybe in EOLANG we should solve this problem? What do you think? It's a little strange that an apple can be equal to a pear, but an error is thrown out when comparing it to a plum.

**Comment by yegor256** [comment]
@EugeneDar what is the proposal?

**Comment by EugeneDar** [comment]
@yegor256 can we check inside eolang if an object has a method? Otherwise, the only solution seems to be to wrap all comparison methods in `try/catch` and return no on error.

**Comment by yegor256** [comment]
@EugeneDar exactly what problem are we solving? Can you show the code?

**Comment by EugeneDar** [comment]
@yegor256 If I understand correctly, eolang allows the same function to return values of different types. So if we have a function where one of the possible return values is 'array', there is no way we can distinguish between the two types without catching an error.

**Comment by yegor256** [comment]
@EugeneDar can you give an example of EO code which fails?

**Comment by EugeneDar** [comment]
@yegor256 
```
# This method gets element by index and returns FALSE if it catches error
[index] > try-at
  if. > @
    index.gte (^.length) // ^ -- `array`
    FALSE
    ^.at index
```

**Comment by yegor256** [comment]
@EugeneDar where exactly is the error? Can you give a full test case which fails (actual case) and explain why it shouldn't fail (expected case)

**Comment by EugeneDar** [comment]
@yegor256 I corrected the last post, please look it up again.

**Comment by EugeneDar** [comment]
@yegor256 "array isn't empty" will never show up on the screen.

**Comment by yegor256** [comment]
@EugeneDar yes, this is not a valid code, since it expects an object to be of two possible types: `bool` and something else. You can't write such code in Java.

**Comment by EugeneDar** [comment]
@yegor256 Okay, I agree, thanks.
