### ISSUE TITLE
`list.with` does not work

### ISSUE THREAD

**Issue by ivan-egorov42** [objectionary/eo-collections#62]
I have this example of code:
```
+alias org.eolang.collections.list
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > app
  list > list1
    * 1 2
  list1.with 3
  seq > @
    []
      stdout > @
        sprintf
          "%d\n"
          list1.at 2
```
The result of a program should be `3`, but there is an error, that `list1` has only two elements:
```
EOorg.EOeolang.EOstringν68="Can't at() the 2th element of the array, there are just 2 of them"SF
```
When I tried to print 0 and 1st elements of `list1` it was OK and I got numbers `1` and `2` respectively.

**Comment by ivan-egorov42** [comment]
@Graur @mximp pls, have a look.

**Comment by Graur** [comment]
@ivan-egorov42 `list.with` creating a new array and do not modifying an old one

**Comment by ivan-egorov42** [comment]
@Graur OK, thanks! I didn't understand description. Now it really works)
