### ISSUE TITLE
list.reduced does not iterate the list

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-collections#63]
@Graur please take a look.
Usually `reduced` does throw every elem in list and executes smth function there. For instance
```
[] > reduced-test-1
  list > l
    * 0 1 2 3
  assert-that > @
    reduced.
      l
      0
      [a x]
        x > @
    $.equal-to 3
```
passes.
But sometimes reduced does not do what we are waiting from it:
```
[] > reduced-test-2
  list > l
    * 0 1 2 3
  reduced. > @
    l
    TRUE
    [a x]
      QQ.io.stdout > @
        "Hi\n"
```
The test above shows
```
[INFO] Running EOorg.EOeolang.EOthreads.EOreduced_test_2Test
Hi
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 s - in EOorg.EOeolang.EOthreads.EOreduced_test_2Test
```
instead of 4 times "Hi\n".
My first hypothesis was it depends on if `a` participates in the function [a x] but the first test proves I am wrong.

**Comment by Graur** [comment]
@levBagryansky Indeed, it is a bug
@includealex please, help to investigate this

**Comment by levBagryansky** [comment]
@includealex `rm -rf ~/.eo` did not help. Updating to the latest version has helped me. Seems the problem was inspired in last weeks by itself.
Thanks
