### ISSUE TITLE
Multimap: redundant parentheses

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo-collections#81]
The multimap contains lots of redundant parentheses:
```java
[WARNING] Redundant parentheses (a.with ((x.at 0).as-hash))
[WARNING] Redundant parentheses (x.at 0)
[WARNING] Redundant parentheses (x.at 0)
```
It would be good to get rid of them.
You can check warnings by using the latest version of `eo-maven-plugin`.
Comes from: https://github.com/objectionary/eo/issues/1490

**Comment by Graur** [comment]
@volodya-lombrozo I believe we solve it here: #88
