### ISSUE TITLE
We need release

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-collections#83]

**Comment by EugeneDar** [comment]
@rultor release `0.0.5`

**Comment by EugeneDar** [comment]
@rultor hello

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#85](https://github.com/objectionary/eo-collections/issues/85) is still not solved.

**Comment by Graur** [comment]
@yegor256 Can you make one more release, please? I want to add new changes to `objectionary/home`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.5`

**Comment by 0pdd** [comment]
@EugeneDar 2 puzzles [#136](https://github.com/objectionary/eo-collections/issues/136), [#85](https://github.com/objectionary/eo-collections/issues/85) are still not solved.
