### ISSUE TITLE
list-tests.eo:36-39: To remove all nop objects from this...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-collections#85]
The puzzle `83-153555c7` from #83 has to be resolved: 

https://github.com/objectionary/eo-collections/blob/34bff4869153ad4e7098344a5b5b827dfcb008ed/src/test/eo/org/eolang/collections/list-tests.eo#L36-L39

The puzzle was created by @Graur on 22-Dec-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Graur** [comment]
@EugeneDar Can you take this task? Maybe this post will help you: https://news.eolang.org/2022-12-22-declarative-while.html

**Comment by EugeneDar** [comment]
@Graur sure.

**Comment by yegor256** [comment]
@maxonfjvipon sure, please!

**Comment by 0pdd** [comment]
@0pdd the puzzle [#136](https://github.com/objectionary/eo-collections/issues/136) is still not solved.
