### ISSUE TITLE
Dataization bug

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-collections#86]
This code should print text 4 times, but it doesn't do it at all.
```
[] > mappedi-printing
  (* 1 2 3 4) > arr!
  mappedi. > method!
    list
      arr
    [x i]
      QQ.io.stdout > @
        "Some test here\n"
  seq > @
    method
    TRUE
```

**Comment by EugeneDar** [comment]
@Graur is this kind of work correct?

**Comment by Graur** [comment]
@EugeneDar No, I believe this code should print text message 4 times

**Comment by EugeneDar** [comment]
@Graur then we should fix it. We need it for this ticket https://github.com/objectionary/eo-collections/issues/85.

**Comment by Graur** [comment]
@EugeneDar but this test didn't fail:
```
[] > mappedi-should-works
  assert-that > @
    mappedi.
      list
        * 1 2 3 4
      [x i]
        x.times 2 > @
    $.equal-to
      list
        * 2 4 6 8
```

Maybe this error is just of `stdout` object?

**Comment by EugeneDar** [comment]
@Graur whatever action I put instead of outputting text, it won't execute once (for example, I tried doing `write` in `memory` objects, but their value didn't change). And this code is more of an example of the problem.

**Comment by EugeneDar** [comment]
@Graur so I think it's a problem with dataization at all, not with `mappedi` only. That's why I gave this ticket name "dataization bug".

**Comment by EugeneDar** [comment]
@Graur @yegor256 can please you assign someone to this ticket, if this is really a bug.

**Comment by maxonfjvipon** [comment]
@yegor256 @Graur @EugeneDar  I don't think there is a bug.
```
[f] > mappedi
  list > @
    ^.reducedi
      *
      [a idx item]
        with. > @
          a
          &.f item idx # <--- no dataization here - just coping
```
So when we apply our "function" we just copy `QQ.io.stdout` with argument `"Some test here\n"` and we say that this new element of the list is decorator of `QQ.io.stdout`

Instead of `mappedi` you can use `each`. Then every `QQ.io.stdout` will be dataized right where it's created

If you want get the result of dataization using `mappedi` you can do:
```
[] > mappedi-printing
  (* 1 2 3 4) > arr!
  mappedi. > method!
    list
      arr
    [x i]
      QQ.io.stdout > @!  # <--- cache here to prevent extra printing
        "Some test here\n"
  assert-that > @
    method
    $.equal-to
      list
        * TRUE TRUE TRUE TRUE
```

Here in order to compare every element of both lists we should dataize them at the beginning and then compare

**Comment by EugeneDar** [comment]
@maxonfjvipon I agree, thank you, I will close this ticket
