### ISSUE TITLE
new eo-collections release

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-collections#89]
We need to produce a new release with this changes #88. Since other repositories had build failures and cannot be released when we specify `failOnWarning` flag. I mean `eo`, `eo-math`, `eo-strings` and etc

**Comment by Graur** [comment]
@yegor256 Can you help?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.6`

**Comment by Graur** [comment]
@yegor256 Can you give it another try?

**Comment by yegor256** [comment]
@Graur maybe it's better to upgrade to EO 0.28.15 first? the bug is fixed there.

**Comment by Graur** [comment]
@yegor256 Sure, I didn't know about it

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.6`

**Comment by Graur** [comment]
@yegor256 Thanks!
