### ISSUE TITLE
list.inflated

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-collections#94]
We have `list.reduce` method, which turns an array+function into a scalar. However, we don't have a reverse operation, which would turn an array+function into a larger array:

```
inflated. > x
  QQ.collections.list
    *
  [a i]
    if. > @
      i.gt 5
      *
      * i 
```

The object encapsulated by `inflated` has two free attributes: `a` is the entire array being inflated, `i` is the incrementing index of the iteration. The object must either dataize to an empty array, which means the end of inflation, or an array, which is appended to `a`.

The result here should be `* 0 1 2 3 4`.

**Comment by yegor256** [comment]
@Graur what do you think?

**Comment by Graur** [comment]
@yegor256 I like the idea!
As far as I know `list.reduce` object was renamed to `list.reduced`. Maybe here we can call our new object `list.inflated`?

**Comment by yegor256** [comment]
@Graur yes, agree, `inflated` is a better name
